services:
  # AI Service (FastAPI)
  - type: web
    name: interviewiq-ai
    runtime: docker
    dockerfilePath: ai-service/Dockerfile
    dockerContext: ai-service
    plan: free
    numInstances: 1
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyAZJfGqRUCq2voHvGDgMSuH__UNUgtvwQI

  # Backend Service (Spring Boot)
  - type: web
    name: interviewiq-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    numInstances: 1
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-4e99f98-thakashiq-268.d.aivencloud.com:26917/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: AVNS_g-HY_irvGBh1W7savhR
      - key: AI_SERVICE_URL
        value: http://interviewiq-ai:8000
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://interviewiq-frontend.onrender.com,http://localhost:5173

  # Frontend Static Site (React + Vite)
  - type: web
    name: interviewiq-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://interviewiq-backend-75hn.onrender.com
